# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fec_utils}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Larson"]
  s.date = %q{2010-04-23}
  s.description = %q{take a look at your govt}
  s.email = %q{thejefflarson@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/fec_utils.rb",
     "lib/fec_utils/itemized_parsers.rb",
     "lib/fec_utils/itemized_parsers/base.rb",
     "lib/fec_utils/itemized_parsers/candidate_parse.rb",
     "lib/fec_utils/itemized_parsers/committee_parse.rb",
     "lib/fec_utils/itemized_parsers/inter_committee_parse.rb",
     "lib/fec_utils/itemized_parsers/pas_parse.rb",
     "test/helper.rb",
     "test/test_fec_utils.rb"
  ]
  s.homepage = %q{http://github.com/thejefflarson/fec_utils}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{fec utilities}
  s.test_files = [
    "test/helper.rb",
     "test/test_fec_utils.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

